/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ConexionBD.ConexionBD;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author scorg
 */
public class AgregarDatosCita extends javax.swing.JFrame {

    private final String codigo;

    /**
     * Creates new form ModificarCitasVista
     * @param codigo
     */
    public AgregarDatosCita(String codigo) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        this.codigo = codigo;
        nombrePaciente.setText(UpdateNombrePaciente(codigo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        jLabeltitle1 = new javax.swing.JLabel();
        jLabeltitle2 = new javax.swing.JLabel();
        nombrePaciente = new javax.swing.JLabel();
        estadoCitaCombo = new ComponentesUI.Combobox();
        jLabeltitle4 = new javax.swing.JLabel();
        codigoEnfermedad = new ComponentesUI.Combobox();
        jLabeltitle5 = new javax.swing.JLabel();
        textAreaScroll2 = new ComponentesUI.TextAreaScroll();
        recomendaciones = new ComponentesUI.TextArea();
        textAreaScroll1 = new ComponentesUI.TextAreaScroll();
        descripcionCita = new ComponentesUI.TextArea();
        textAreaScroll3 = new ComponentesUI.TextAreaScroll();
        tratamiento = new ComponentesUI.TextArea();
        jLabeltitle3 = new javax.swing.JLabel();
        jLabeltitle6 = new javax.swing.JLabel();
        botonGuardar = new ComponentesUI.Button();
        botonRegresar = new ComponentesUI.Button();
        jLabel2 = new javax.swing.JLabel();
        tipoCitaCombo = new ComponentesUI.Combobox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar reporte a cita");

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabeltitle.setText("Reporte");
        bg.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 349, -1));

        jLabeltitle1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabeltitle1.setText("Agregar reporte a cita");
        bg.add(jLabeltitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 400, -1));

        jLabeltitle2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltitle2.setText("Paciente:");
        bg.add(jLabeltitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        nombrePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nombrePaciente.setText("(Nombre paciente)");
        bg.add(nombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 349, -1));

        estadoCitaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDIENTE", "COMPLETADA", "INCUMPLIDA", "CANCELADA" }));
        estadoCitaCombo.setToolTipText("");
        estadoCitaCombo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        estadoCitaCombo.setLabeText("");
        estadoCitaCombo.setLineColor(new java.awt.Color(0, 153, 153));
        bg.add(estadoCitaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 160, 40));

        jLabeltitle4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltitle4.setText("Tipo de cita");
        bg.add(jLabeltitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 100, -1));

        codigoEnfermedad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A02", "A03" }));
        codigoEnfermedad.setToolTipText("");
        codigoEnfermedad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        codigoEnfermedad.setLabeText("");
        codigoEnfermedad.setLineColor(new java.awt.Color(0, 153, 153));
        bg.add(codigoEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 270, 40));

        jLabeltitle5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltitle5.setText("Estado");
        bg.add(jLabeltitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 100, -1));

        textAreaScroll2.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        textAreaScroll2.setLabelText("Recomendaciones");

        recomendaciones.setColumns(20);
        recomendaciones.setRows(5);
        recomendaciones.setDisabledTextColor(new java.awt.Color(102, 0, 204));
        recomendaciones.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        recomendaciones.setSelectionColor(new java.awt.Color(0, 153, 153));
        textAreaScroll2.setViewportView(recomendaciones);

        bg.add(textAreaScroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 260, 150));

        textAreaScroll1.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        textAreaScroll1.setLabelText("Descripción de la cita");

        descripcionCita.setColumns(20);
        descripcionCita.setRows(5);
        descripcionCita.setDisabledTextColor(new java.awt.Color(102, 0, 204));
        descripcionCita.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        descripcionCita.setSelectionColor(new java.awt.Color(0, 153, 153));
        textAreaScroll1.setViewportView(descripcionCita);

        bg.add(textAreaScroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 520, 150));

        textAreaScroll3.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        textAreaScroll3.setLabelText("Tratamiento");

        tratamiento.setColumns(20);
        tratamiento.setRows(5);
        tratamiento.setDisabledTextColor(new java.awt.Color(102, 0, 204));
        tratamiento.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        tratamiento.setSelectionColor(new java.awt.Color(0, 153, 153));
        textAreaScroll3.setViewportView(tratamiento);

        bg.add(textAreaScroll3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 260, 150));

        jLabeltitle3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabeltitle3.setText("Datos cita");
        bg.add(jLabeltitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 349, -1));

        jLabeltitle6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabeltitle6.setText("Diágnostico");
        bg.add(jLabeltitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 280, -1));

        botonGuardar.setBackground(new java.awt.Color(78, 158, 185));
        botonGuardar.setForeground(new java.awt.Color(244, 240, 238));
        botonGuardar.setText("Guardar");
        botonGuardar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        bg.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 270, 48));

        botonRegresar.setBackground(new java.awt.Color(78, 158, 185));
        botonRegresar.setForeground(new java.awt.Color(244, 240, 238));
        botonRegresar.setText("Regresar");
        botonRegresar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        bg.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 153, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineasFondo.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, -1));

        tipoCitaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CONSULTA", "EXAMEN", "CIRUGIA" }));
        tipoCitaCombo.setToolTipText("");
        tipoCitaCombo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tipoCitaCombo.setLabeText("");
        tipoCitaCombo.setLineColor(new java.awt.Color(0, 153, 153));
        bg.add(tipoCitaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String UpdateNombrePaciente(String codigo){
    
        return ConexionBD.consultarNombre(codigo);       
    }
    
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        try {

            long identificadorCita = Long.parseLong(codigo);
            String descripcionCitaa = descripcionCita.getText();
            String tipoCita = tipoCitaCombo.getSelectedItem().toString();
            String tratamientoo = tratamiento.getText();
            String recomendacioness = recomendaciones.getText();
            String estadoCita = estadoCitaCombo.getSelectedItem().toString();
            String codEnfermedad = codigoEnfermedad.getSelectedItem().toString();

            if (recomendacioness.isEmpty() || tratamientoo.isEmpty() || descripcionCitaa.isEmpty()) {
                throw new NullPointerException("Campos vacios");
            }

            ConexionBD.modificarCita(identificadorCita, descripcionCitaa, tipoCita,
                    tratamientoo, recomendacioness, estadoCita, codEnfermedad);
            JOptionPane.showMessageDialog(this, "Reporte guardado correctamente");
            this.dispose();
            

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error de tipo de dato");
        } 
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        GestionarCitasVista ventana = new GestionarCitasVista();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private ComponentesUI.Button botonGuardar;
    private ComponentesUI.Button botonRegresar;
    private ComponentesUI.Combobox codigoEnfermedad;
    private ComponentesUI.TextArea descripcionCita;
    private ComponentesUI.Combobox estadoCitaCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JLabel jLabeltitle1;
    private javax.swing.JLabel jLabeltitle2;
    private javax.swing.JLabel jLabeltitle3;
    private javax.swing.JLabel jLabeltitle4;
    private javax.swing.JLabel jLabeltitle5;
    private javax.swing.JLabel jLabeltitle6;
    public static javax.swing.JLabel nombrePaciente;
    private ComponentesUI.TextArea recomendaciones;
    private ComponentesUI.TextAreaScroll textAreaScroll1;
    private ComponentesUI.TextAreaScroll textAreaScroll2;
    private ComponentesUI.TextAreaScroll textAreaScroll3;
    private ComponentesUI.Combobox tipoCitaCombo;
    private ComponentesUI.TextArea tratamiento;
    // End of variables declaration//GEN-END:variables
}
