/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Santiago Cortés
 */
public class CancelarCitaVista extends javax.swing.JFrame {

    /**
     * Creates new form VerHorarioVista
     */
    public CancelarCitaVista() {
        initComponents();
        UpdateCitasList();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        botonCancelar = new ComponentesUI.Button();
        botonAgendarCita = new ComponentesUI.Button();
        citasPaciente = new ComponentesUI.Combobox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Horario");
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabeltitle.setText("Cancelar cita");
        bg.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 349, -1));

        botonCancelar.setBackground(new java.awt.Color(78, 158, 185));
        botonCancelar.setForeground(new java.awt.Color(244, 240, 238));
        botonCancelar.setText("Cancelar");
        botonCancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        bg.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 320, 48));

        botonAgendarCita.setBackground(new java.awt.Color(78, 158, 185));
        botonAgendarCita.setForeground(new java.awt.Color(244, 240, 238));
        botonAgendarCita.setText("Cancelar cita");
        botonAgendarCita.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgendarCitaActionPerformed(evt);
            }
        });
        bg.add(botonAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 320, 48));

        citasPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cod: 231,2022-11-02, Consulta", "Cod: 120, 2022-12-05, Cirugia", " ", " " }));
        citasPaciente.setToolTipText("");
        citasPaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        citasPaciente.setLabeText("");
        citasPaciente.setLineColor(new java.awt.Color(0, 153, 153));
        bg.add(citasPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineasFondo.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, -1, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void UpdateCitasList(){
        String[] citas = ConexionBD.ConexionBD.consultarCitas();
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(citas);
        citasPaciente.setModel(comboBoxModel);
    }
    
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        MenuPaciente ventana = new MenuPaciente();
        ventana.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgendarCitaActionPerformed
        // TODO add your handling code here:
        String tosplit =citasPaciente.getSelectedItem().toString();
        String[] words = tosplit.split(",");
        String[] codYs = words[0].split(":");
        long elCodigo = Long.parseLong(codYs[1]);
        int log = ConexionBD.ConexionBD.cancelarCita(elCodigo);
        System.out.println(log);
        this.dispose();
    }//GEN-LAST:event_botonAgendarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private ComponentesUI.Button botonAgendarCita;
    private ComponentesUI.Button botonCancelar;
    private ComponentesUI.Combobox citasPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabeltitle;
    // End of variables declaration//GEN-END:variables
}
