/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Fuentes.Fuente;



/**
 *
 * @author Santiago Cortés
 */
public class CrearUsuarioVista extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuarioVista
     */
    public CrearUsuarioVista() {
        initComponents();
        Fuente.aplicarFuente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        botonRegresar = new ComponentesUI.Button();
        botonCrearMedico = new ComponentesUI.Button();
        botonCrearPaciente = new ComponentesUI.Button();
        jLabeltitle = new javax.swing.JLabel();
        jLabeltext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear nuevo usuario");

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar.setBackground(new java.awt.Color(78, 158, 185));
        botonRegresar.setForeground(new java.awt.Color(244, 240, 238));
        botonRegresar.setText("Regresar");
        botonRegresar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        bg.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 112, 48));

        botonCrearMedico.setBackground(new java.awt.Color(78, 158, 185));
        botonCrearMedico.setForeground(new java.awt.Color(244, 240, 238));
        botonCrearMedico.setText("Médico");
        botonCrearMedico.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonCrearMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearMedicoActionPerformed(evt);
            }
        });
        bg.add(botonCrearMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 48));

        botonCrearPaciente.setBackground(new java.awt.Color(78, 158, 185));
        botonCrearPaciente.setForeground(new java.awt.Color(244, 240, 238));
        botonCrearPaciente.setText("Paciente");
        botonCrearPaciente.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonCrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPacienteActionPerformed(evt);
            }
        });
        bg.add(botonCrearPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 200, 48));

        jLabeltitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabeltitle.setText("Crear nuevo usuario");
        jLabeltext.setName("jlabeltitle");
        bg.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 349, -1));

        jLabeltext.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltext.setText("Elija el tipo de usuario que creará.");
        jLabeltext.setName("jlabeltext");
        bg.add(jLabeltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crearUsuario.png"))); // NOI18N
        jLabel1.setOpaque(true);
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(706, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        LoginVista ventana = new LoginVista();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonCrearMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearMedicoActionPerformed
        // TODO add your handling code here:
        CrearMedicoVista ventanaCrearMedico = new CrearMedicoVista();
        ventanaCrearMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearMedicoActionPerformed

    private void botonCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPacienteActionPerformed
        // TODO add your handling code here:
        CrearPacienteVista ventana = new CrearPacienteVista();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuarioVista().setVisible(true);
                        

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private ComponentesUI.Button botonCrearMedico;
    private ComponentesUI.Button botonCrearPaciente;
    private ComponentesUI.Button botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabeltext;
    private javax.swing.JLabel jLabeltitle;
    // End of variables declaration//GEN-END:variables
}
