/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago Cortés
 */
public class CrearPacienteVista extends javax.swing.JFrame {
    private File historyFile = null;
    /**
     * Creates new form Login
     */
    public CrearPacienteVista() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombrePaciente = new ComponentesUI.TextField();
        campoApellidosPaciente = new ComponentesUI.TextField();
        campoCedulaPaciente = new ComponentesUI.TextField();
        campoTelefonoPaciente = new ComponentesUI.TextField();
        campoCorreoPaciente = new ComponentesUI.TextField();
        campoContraseñaPaciente = new CampoContraseña.PasswordField();
        jchooser = new com.toedter.calendar.JDateChooser();
        grupoSanguineo = new ComponentesUI.Combobox();
        factorRH = new ComponentesUI.Combobox();
        campoDireccionPaciente = new ComponentesUI.TextField();
        campoFechaNacimiento = new ComponentesUI.TextField();
        alergias = new ComponentesUI.RadioButtonCustom();
        enfermedades = new ComponentesUI.RadioButtonCustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoContraseñaPaciente2 = new CampoContraseña.PasswordField();
        jLabel5 = new javax.swing.JLabel();
        botonRegresar = new ComponentesUI.Button();
        botonSubirHistoria = new ComponentesUI.Button();
        botonCrearPaciente = new ComponentesUI.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear nuevo paciente");
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabeltitle.setText("Crear nuevo paciente");
        bg.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 400, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("¿Alergias?");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        campoNombrePaciente.setBackground(new java.awt.Color(252, 252, 252));
        campoNombrePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoNombrePaciente.setShadowColor(new java.awt.Color(0, 153, 153));
        campoNombrePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombrePacienteMouseClicked(evt);
            }
        });
        campoNombrePaciente.setPlaceholder("Nombres...");
        bg.add(campoNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 256, 47));

        campoApellidosPaciente.setBackground(new java.awt.Color(252, 252, 252));
        campoApellidosPaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoApellidosPaciente.setShadowColor(new java.awt.Color(0, 153, 153));
        campoApellidosPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidosPacienteMouseClicked(evt);
            }
        });
        campoApellidosPaciente.setPlaceholder("Apellidos...");
        bg.add(campoApellidosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 256, 47));

        campoCedulaPaciente.setBackground(new java.awt.Color(252, 252, 252));
        campoCedulaPaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoCedulaPaciente.setShadowColor(new java.awt.Color(0, 153, 153));
        campoCedulaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCedulaPacienteMouseClicked(evt);
            }
        });
        campoCedulaPaciente.setPlaceholder("Cédula...");
        bg.add(campoCedulaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 256, 47));

        campoTelefonoPaciente.setBackground(new java.awt.Color(252, 252, 252));
        campoTelefonoPaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoTelefonoPaciente.setShadowColor(new java.awt.Color(0, 153, 153));
        campoTelefonoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoTelefonoPacienteMouseClicked(evt);
            }
        });
        campoTelefonoPaciente.setPlaceholder("Teléfono...");
        bg.add(campoTelefonoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 256, 47));

        campoCorreoPaciente.setBackground(new java.awt.Color(252, 252, 252));
        campoCorreoPaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoCorreoPaciente.setShadowColor(new java.awt.Color(0, 153, 153));
        campoCorreoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCorreoPacienteMouseClicked(evt);
            }
        });
        campoCorreoPaciente.setPlaceholder("Correo...");
        bg.add(campoCorreoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 256, 47));

        campoContraseñaPaciente.setBackground(new java.awt.Color(252, 252, 252));
        campoContraseñaPaciente.setText("campoContraseña");
        campoContraseñaPaciente.setShadowColor(new java.awt.Color(0, 153, 153));
        bg.add(campoContraseñaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 260, 50));

        jchooser.setBackground(new java.awt.Color(255, 255, 255));
        jchooser.setToolTipText("");
        jchooser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jchooserInputMethodTextChanged(evt);
            }
        });
        jchooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jchooserPropertyChange(evt);
            }
        });
        bg.add(jchooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 44, 39));

        grupoSanguineo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "AB", "B", "O" }));
        grupoSanguineo.setToolTipText("");
        grupoSanguineo.setLabeText("Grupo sanguíneo");
        grupoSanguineo.setLineColor(new java.awt.Color(0, 153, 153));
        grupoSanguineo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoSanguineoActionPerformed(evt);
            }
        });
        bg.add(grupoSanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 129, 50));

        factorRH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        factorRH.setLabeText("RH");
        factorRH.setLineColor(new java.awt.Color(0, 153, 153));
        factorRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorRHActionPerformed(evt);
            }
        });
        bg.add(factorRH, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 52, 50));

        campoDireccionPaciente.setBackground(new java.awt.Color(252, 252, 252));
        campoDireccionPaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoDireccionPaciente.setShadowColor(new java.awt.Color(0, 153, 153));
        campoDireccionPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoDireccionPacienteMouseClicked(evt);
            }
        });
        campoDireccionPaciente.setPlaceholder("Dirección...");
        bg.add(campoDireccionPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 256, 47));

        campoFechaNacimiento.setBackground(new java.awt.Color(252, 252, 252));
        campoFechaNacimiento.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoFechaNacimiento.setShadowColor(new java.awt.Color(0, 153, 153));
        campoFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoFechaNacimientoMouseClicked(evt);
            }
        });
        campoFechaNacimiento.setPlaceholder("Fecha de nacimiento...");
        bg.add(campoFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 190, 47));

        alergias.setText("Si");
        alergias.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        alergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergiasActionPerformed(evt);
            }
        });
        bg.add(alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        enfermedades.setText("Si");
        enfermedades.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        enfermedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermedadesActionPerformed(evt);
            }
        });
        bg.add(enfermedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("¿Enfermedades preexistentes?");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 240, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        campoContraseñaPaciente2.setBackground(new java.awt.Color(252, 252, 252));
        campoContraseñaPaciente2.setText("campoContraseña");
        campoContraseñaPaciente2.setShadowColor(new java.awt.Color(0, 153, 153));
        bg.add(campoContraseñaPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 260, 50));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Repita su contraseña");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        botonRegresar.setBackground(new java.awt.Color(78, 158, 185));
        botonRegresar.setForeground(new java.awt.Color(244, 240, 238));
        botonRegresar.setText("Regresar");
        botonRegresar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        bg.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 153, 48));

        botonSubirHistoria.setBackground(new java.awt.Color(78, 158, 185));
        botonSubirHistoria.setForeground(new java.awt.Color(244, 240, 238));
        botonSubirHistoria.setText("Subir historia clinica(opcional)");
        botonSubirHistoria.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonSubirHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirHistoriaActionPerformed(evt);
            }
        });
        bg.add(botonSubirHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 250, 48));

        botonCrearPaciente.setBackground(new java.awt.Color(78, 158, 185));
        botonCrearPaciente.setForeground(new java.awt.Color(244, 240, 238));
        botonCrearPaciente.setText("Crear paciente");
        botonCrearPaciente.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonCrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPacienteActionPerformed(evt);
            }
        });
        bg.add(botonCrearPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 220, 48));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/paciente.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 310, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String getFileExtension(File file) {
    String name = file.getName();
    int lastIndexOf = name.lastIndexOf(".");
    if (lastIndexOf == -1) {
        return ""; // empty extension
    }
    return name.substring(lastIndexOf);
}
    
    private void campoNombrePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombrePacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombrePacienteMouseClicked

    private void campoApellidosPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidosPacienteMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_campoApellidosPacienteMouseClicked

    private void campoCedulaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCedulaPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaPacienteMouseClicked

    private void campoTelefonoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoTelefonoPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoPacienteMouseClicked

    private void campoCorreoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCorreoPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoPacienteMouseClicked

    private void campoDireccionPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDireccionPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionPacienteMouseClicked

    private void campoFechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoFechaNacimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaNacimientoMouseClicked

    private void jchooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jchooserPropertyChange
        // TODO add your handling code here:
        Date selectedDate = jchooser.getDate();

        if (selectedDate != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = dateFormat.format(selectedDate);
            campoFechaNacimiento.setText(formattedDate);
        }

    }//GEN-LAST:event_jchooserPropertyChange

    private void jchooserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jchooserInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jchooserInputMethodTextChanged

    private void alergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergiasActionPerformed

    private void enfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermedadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfermedadesActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        CrearUsuarioVista ventana = new CrearUsuarioVista();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonSubirHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirHistoriaActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this); // Muestra el diálogo de selección de archivos

        // Aquí puedes hacer algo con el archivo seleccionado, como mostrar su nombre en un JLabel o realizar alguna operación con él.
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String extension = getFileExtension(selectedFile);
            if( extension.equals(".txt") || extension.equals(".doc") || extension.equals(".pdf")){
            
                historyFile = selectedFile;
            }else{
            JOptionPane.showMessageDialog(null, "Su archivo debe estar en formato txt, doc o pdf " , "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_botonSubirHistoriaActionPerformed

    private void botonCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPacienteActionPerformed
        // TODO add your handling code here:
        try{
            String elNombre = campoNombrePaciente.getText();
            String Apellidos = campoApellidosPaciente.getText();
            int laCedula = Integer.parseInt(campoCedulaPaciente.getText());
            int elTelefono = Integer.parseInt(campoTelefonoPaciente.getText());
            String elCorreo = campoCorreoPaciente.getText();
            String laFechaNac = campoFechaNacimiento.getText();
            boolean lasEnfermedades = enfermedades.isSelected();
            boolean lasAlergias = alergias.isSelected();
            String elGrupoSagnguineo = grupoSanguineo.getSelectedItem().toString() + factorRH.getSelectedItem().toString(); 
            String laDireccion = campoDireccionPaciente.getText();
            String pass1 = new String(campoContraseñaPaciente.getPassword());
            String pass2 = new String(campoContraseñaPaciente2.getPassword());
            if (!pass1.equals(pass2)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        }else{
        ConexionBD.ConexionBD.crearPaciente(elNombre,Apellidos,laCedula,elTelefono, elCorreo, laFechaNac,lasEnfermedades,lasAlergias,elGrupoSagnguineo,laDireccion,pass1,historyFile);
        }            
        }catch(NullPointerException | NumberFormatException | IOException e){
        JOptionPane.showMessageDialog(null, "Error al crear el paciente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);         
        }
    }//GEN-LAST:event_botonCrearPacienteActionPerformed

    private void factorRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorRHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factorRHActionPerformed

    private void grupoSanguineoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoSanguineoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoSanguineoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPacienteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComponentesUI.RadioButtonCustom alergias;
    private javax.swing.JPanel bg;
    private ComponentesUI.Button botonCrearPaciente;
    private ComponentesUI.Button botonRegresar;
    private ComponentesUI.Button botonSubirHistoria;
    private ComponentesUI.TextField campoApellidosPaciente;
    private ComponentesUI.TextField campoCedulaPaciente;
    private CampoContraseña.PasswordField campoContraseñaPaciente;
    private CampoContraseña.PasswordField campoContraseñaPaciente2;
    private ComponentesUI.TextField campoCorreoPaciente;
    private ComponentesUI.TextField campoDireccionPaciente;
    private ComponentesUI.TextField campoFechaNacimiento;
    private ComponentesUI.TextField campoNombrePaciente;
    private ComponentesUI.TextField campoTelefonoPaciente;
    private ComponentesUI.RadioButtonCustom enfermedades;
    private ComponentesUI.Combobox factorRH;
    private ComponentesUI.Combobox grupoSanguineo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabeltitle;
    private com.toedter.calendar.JDateChooser jchooser;
    // End of variables declaration//GEN-END:variables
}
