/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Santiago Cortés
 */
public class CrearMedicoVista extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public CrearMedicoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        campoApellidosMedico = new ComponentesUI.TextField();
        campoNombreMedico = new ComponentesUI.TextField();
        campoCedulaMedico = new ComponentesUI.TextField();
        campoTelefonoMedico = new ComponentesUI.TextField();
        campoCorreoMedico = new ComponentesUI.TextField();
        campoEspecialidadMedico = new ComponentesUI.TextField();
        campoTarifa = new ComponentesUI.TextField();
        botonCrearMedico = new ComponentesUI.Button();
        botonCrearMedico1 = new ComponentesUI.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoContraseñaMedico2 = new CampoContraseña.PasswordField();
        jLabel1 = new javax.swing.JLabel();
        campoContraseñaMedico = new CampoContraseña.PasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear nuevo médico");

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabeltitle.setText("Crear nuevo médico");
        bg.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 349, -1));

        campoApellidosMedico.setBackground(new java.awt.Color(252, 252, 252));
        campoApellidosMedico.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoApellidosMedico.setShadowColor(new java.awt.Color(0, 153, 153));
        campoApellidosMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidosMedicoMouseClicked(evt);
            }
        });
        campoApellidosMedico.setPlaceholder("Apellidos...");
        bg.add(campoApellidosMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 256, 47));

        campoNombreMedico.setBackground(new java.awt.Color(252, 252, 252));
        campoNombreMedico.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoNombreMedico.setShadowColor(new java.awt.Color(0, 153, 153));
        campoNombreMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMedicoMouseClicked(evt);
            }
        });
        campoNombreMedico.setPlaceholder("Nombres...");
        bg.add(campoNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 256, 47));

        campoCedulaMedico.setBackground(new java.awt.Color(252, 252, 252));
        campoCedulaMedico.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoCedulaMedico.setShadowColor(new java.awt.Color(0, 153, 153));
        campoCedulaMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCedulaMedicoMouseClicked(evt);
            }
        });
        campoCedulaMedico.setPlaceholder("Cédula...");
        bg.add(campoCedulaMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 256, 47));

        campoTelefonoMedico.setBackground(new java.awt.Color(252, 252, 252));
        campoTelefonoMedico.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoTelefonoMedico.setShadowColor(new java.awt.Color(0, 153, 153));
        campoTelefonoMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoTelefonoMedicoMouseClicked(evt);
            }
        });
        campoTelefonoMedico.setPlaceholder("Teléfono...");
        bg.add(campoTelefonoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 256, 47));

        campoCorreoMedico.setBackground(new java.awt.Color(252, 252, 252));
        campoCorreoMedico.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoCorreoMedico.setShadowColor(new java.awt.Color(0, 153, 153));
        campoCorreoMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCorreoMedicoMouseClicked(evt);
            }
        });
        campoCorreoMedico.setPlaceholder("Correo...");
        bg.add(campoCorreoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 256, 47));

        campoEspecialidadMedico.setBackground(new java.awt.Color(252, 252, 252));
        campoEspecialidadMedico.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoEspecialidadMedico.setShadowColor(new java.awt.Color(0, 153, 153));
        campoEspecialidadMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoEspecialidadMedicoMouseClicked(evt);
            }
        });
        campoEspecialidadMedico.setPlaceholder("Especialidad...");
        bg.add(campoEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 256, 47));

        campoTarifa.setBackground(new java.awt.Color(252, 252, 252));
        campoTarifa.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoTarifa.setShadowColor(new java.awt.Color(0, 153, 153));
        campoTarifa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoTarifaMouseClicked(evt);
            }
        });
        campoTarifa.setPlaceholder("Tarifa por hora...");
        bg.add(campoTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 256, 50));

        botonCrearMedico.setBackground(new java.awt.Color(78, 158, 185));
        botonCrearMedico.setForeground(new java.awt.Color(244, 240, 238));
        botonCrearMedico.setText("Regresar");
        botonCrearMedico.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonCrearMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearMedicoActionPerformed(evt);
            }
        });
        bg.add(botonCrearMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 153, 48));

        botonCrearMedico1.setBackground(new java.awt.Color(78, 158, 185));
        botonCrearMedico1.setForeground(new java.awt.Color(244, 240, 238));
        botonCrearMedico1.setText("Crear médico");
        botonCrearMedico1.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonCrearMedico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearMedico1ActionPerformed(evt);
            }
        });
        bg.add(botonCrearMedico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 260, 48));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Repita su contraseña");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        campoContraseñaMedico2.setBackground(new java.awt.Color(252, 252, 252));
        campoContraseñaMedico2.setText("passwordField1");
        campoContraseñaMedico2.setShadowColor(new java.awt.Color(0, 153, 153));
        bg.add(campoContraseñaMedico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medico.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        campoContraseñaMedico.setBackground(new java.awt.Color(252, 252, 252));
        campoContraseñaMedico.setText("passwordField1");
        campoContraseñaMedico.setShadowColor(new java.awt.Color(0, 153, 153));
        bg.add(campoContraseñaMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoApellidosMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidosMedicoMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campoApellidosMedicoMouseClicked

    private void campoNombreMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMedicoMouseClicked

    private void campoCedulaMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCedulaMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaMedicoMouseClicked

    private void campoTelefonoMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoTelefonoMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoMedicoMouseClicked

    private void campoCorreoMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCorreoMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoMedicoMouseClicked

    private void campoEspecialidadMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoEspecialidadMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEspecialidadMedicoMouseClicked

    private void campoTarifaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoTarifaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTarifaMouseClicked

    private void botonCrearMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearMedicoActionPerformed
        // TODO add your handling code here:
        CrearUsuarioVista ventana = new CrearUsuarioVista();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearMedicoActionPerformed

    private void botonCrearMedico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearMedico1ActionPerformed
        // TODO add your handling code here:
        int laCedula = Integer.parseInt(campoCedulaMedico.getText());
        String elNombre = campoNombreMedico.getText();
        String Apellidos = campoApellidosMedico.getText();
        int  elTelefono = Integer.parseInt(campoTelefonoMedico.getText());
        String laEspecialidad = campoEspecialidadMedico.getText();
        String elCorreo= campoCorreoMedico.getText();
        float laTarifa = Float.parseFloat(campoTarifa.getText());
        String contraseña = new String(campoContraseñaMedico.getPassword());
        String confirmarContraseña = new String(campoContraseñaMedico2.getPassword());
        if (!contraseña.equals(confirmarContraseña)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        }else{
        ConexionBD.ConexionBD.crearMedico(laCedula, elNombre, Apellidos, contraseña, elTelefono, laEspecialidad, elCorreo, laTarifa);
        }
        
    }//GEN-LAST:event_botonCrearMedico1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearMedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearMedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearMedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearMedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearMedicoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private ComponentesUI.Button botonCrearMedico;
    private ComponentesUI.Button botonCrearMedico1;
    private ComponentesUI.TextField campoApellidosMedico;
    private ComponentesUI.TextField campoCedulaMedico;
    private CampoContraseña.PasswordField campoContraseñaMedico;
    private CampoContraseña.PasswordField campoContraseñaMedico2;
    private ComponentesUI.TextField campoCorreoMedico;
    private ComponentesUI.TextField campoEspecialidadMedico;
    private ComponentesUI.TextField campoNombreMedico;
    private ComponentesUI.TextField campoTarifa;
    private ComponentesUI.TextField campoTelefonoMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabeltitle;
    // End of variables declaration//GEN-END:variables
}
