/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Santiago Cortés
 */
public class MenuPaciente extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MenuPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        jLabeltext = new javax.swing.JLabel();
        botonAgendarCitas = new ComponentesUI.Button();
        botonCancelarCita = new ComponentesUI.Button();
        botonConsultarCitas = new ComponentesUI.Button();
        botonSalir = new ComponentesUI.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú pacientes");
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabeltitle.setText("¿Qué desea hacer?");
        bg.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 349, -1));

        jLabeltext.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltext.setText("Seleccione una opción del menú.");
        jLabeltext.setName("jlabeltext");
        bg.add(jLabeltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        botonAgendarCitas.setBackground(new java.awt.Color(78, 158, 185));
        botonAgendarCitas.setForeground(new java.awt.Color(244, 240, 238));
        botonAgendarCitas.setText("Agendar cita");
        botonAgendarCitas.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonAgendarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgendarCitasActionPerformed(evt);
            }
        });
        bg.add(botonAgendarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 210, 48));

        botonCancelarCita.setBackground(new java.awt.Color(78, 158, 185));
        botonCancelarCita.setForeground(new java.awt.Color(244, 240, 238));
        botonCancelarCita.setText("Cancelar cita");
        botonCancelarCita.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarCitaActionPerformed(evt);
            }
        });
        bg.add(botonCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 210, 48));

        botonConsultarCitas.setBackground(new java.awt.Color(78, 158, 185));
        botonConsultarCitas.setForeground(new java.awt.Color(244, 240, 238));
        botonConsultarCitas.setText("Consultar citas");
        botonConsultarCitas.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonConsultarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarCitasActionPerformed(evt);
            }
        });
        bg.add(botonConsultarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 210, 48));

        botonSalir.setBackground(new java.awt.Color(78, 158, 185));
        botonSalir.setForeground(new java.awt.Color(244, 240, 238));
        botonSalir.setText("Salir");
        botonSalir.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        bg.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 210, 48));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineasFondo.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgendarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgendarCitasActionPerformed
        // TODO add your handling code here:
        AgendarCita ventanaAgendar = new AgendarCita();
        ventanaAgendar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAgendarCitasActionPerformed

    private void botonCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarCitaActionPerformed
        // TODO add your handling code here:
        CancelarCitaVista ventana = new CancelarCitaVista();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCancelarCitaActionPerformed

    private void botonConsultarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarCitasActionPerformed
        // TODO add your handling code here:
        ConsultarCitas ventana = new ConsultarCitas();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonConsultarCitasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private ComponentesUI.Button botonAgendarCitas;
    private ComponentesUI.Button botonCancelarCita;
    private ComponentesUI.Button botonConsultarCitas;
    private ComponentesUI.Button botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabeltext;
    private javax.swing.JLabel jLabeltitle;
    // End of variables declaration//GEN-END:variables
}
