/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author scorg
 */
public class ModificarCitaVista extends javax.swing.JFrame {

    /**
     * Creates new form ModificarCitasVista
     */
    public ModificarCitaVista() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        jLabeltitle1 = new javax.swing.JLabel();
        jLabeltitle2 = new javax.swing.JLabel();
        nombrePaciente = new javax.swing.JLabel();
        estadoCita = new ComponentesUI.Combobox();
        jLabeltitle4 = new javax.swing.JLabel();
        tipoCita = new ComponentesUI.Combobox();
        jLabeltitle5 = new javax.swing.JLabel();
        textAreaScroll2 = new ComponentesUI.TextAreaScroll();
        recomendaciones = new ComponentesUI.TextArea();
        textAreaScroll1 = new ComponentesUI.TextAreaScroll();
        descripcionCita = new ComponentesUI.TextArea();
        textAreaScroll3 = new ComponentesUI.TextAreaScroll();
        tratamiento = new ComponentesUI.TextArea();
        jLabeltitle3 = new javax.swing.JLabel();
        jLabeltitle6 = new javax.swing.JLabel();
        botonGuardar = new ComponentesUI.Button();
        botonRegresar = new ComponentesUI.Button();
        jLabel2 = new javax.swing.JLabel();
        codigoEnfermedad = new ComponentesUI.TextField();
        jchooser = new com.toedter.calendar.JDateChooser();
        campoFechaCita = new ComponentesUI.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar cita");

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabeltitle.setText("Reporte");
        bg.add(jLabeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 349, -1));

        jLabeltitle1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabeltitle1.setText("Modificar cita");
        bg.add(jLabeltitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 349, -1));

        jLabeltitle2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltitle2.setText("Paciente:");
        bg.add(jLabeltitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        nombrePaciente.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nombrePaciente.setText("(Nombre paciente)");
        bg.add(nombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 349, -1));

        estadoCita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendiente", "Completada", "Incumplida", "Cancelada" }));
        estadoCita.setToolTipText("");
        estadoCita.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        estadoCita.setLabeText("");
        estadoCita.setLineColor(new java.awt.Color(0, 153, 153));
        bg.add(estadoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 160, 40));

        jLabeltitle4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltitle4.setText("Tipo de cita");
        bg.add(jLabeltitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 100, -1));

        tipoCita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consulta", "Exámen", "Cirugía" }));
        tipoCita.setToolTipText("");
        tipoCita.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tipoCita.setLabeText("");
        tipoCita.setLineColor(new java.awt.Color(0, 153, 153));
        bg.add(tipoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, 40));

        jLabeltitle5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabeltitle5.setText("Estado");
        bg.add(jLabeltitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 100, -1));

        textAreaScroll2.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        textAreaScroll2.setLabelText("Recomendaciones");

        recomendaciones.setColumns(20);
        recomendaciones.setRows(5);
        recomendaciones.setDisabledTextColor(new java.awt.Color(102, 0, 204));
        recomendaciones.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        recomendaciones.setSelectionColor(new java.awt.Color(0, 153, 153));
        textAreaScroll2.setViewportView(recomendaciones);

        bg.add(textAreaScroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 260, 150));

        textAreaScroll1.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        textAreaScroll1.setLabelText("Descripción de la cita");

        descripcionCita.setColumns(20);
        descripcionCita.setRows(5);
        descripcionCita.setDisabledTextColor(new java.awt.Color(102, 0, 204));
        descripcionCita.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        descripcionCita.setSelectionColor(new java.awt.Color(0, 153, 153));
        textAreaScroll1.setViewportView(descripcionCita);

        bg.add(textAreaScroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 520, 150));

        textAreaScroll3.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        textAreaScroll3.setLabelText("Tratamiento");

        tratamiento.setColumns(20);
        tratamiento.setRows(5);
        tratamiento.setDisabledTextColor(new java.awt.Color(102, 0, 204));
        tratamiento.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        tratamiento.setSelectionColor(new java.awt.Color(0, 153, 153));
        textAreaScroll3.setViewportView(tratamiento);

        bg.add(textAreaScroll3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 260, 150));

        jLabeltitle3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabeltitle3.setText("Datos cita");
        bg.add(jLabeltitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 349, -1));

        jLabeltitle6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabeltitle6.setText("Diágnostico");
        bg.add(jLabeltitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 280, -1));

        botonGuardar.setBackground(new java.awt.Color(78, 158, 185));
        botonGuardar.setForeground(new java.awt.Color(244, 240, 238));
        botonGuardar.setText("Guardar");
        botonGuardar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        bg.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 270, 48));

        botonRegresar.setBackground(new java.awt.Color(78, 158, 185));
        botonRegresar.setForeground(new java.awt.Color(244, 240, 238));
        botonRegresar.setText("Regresar");
        botonRegresar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        bg.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 153, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineasFondo.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, -1));

        codigoEnfermedad.setBackground(new java.awt.Color(252, 252, 252));
        codigoEnfermedad.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        codigoEnfermedad.setShadowColor(new java.awt.Color(0, 153, 153));
        codigoEnfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoEnfermedadMouseClicked(evt);
            }
        });
        codigoEnfermedad.setPlaceholder("Código de la enfermedad...");
        bg.add(codigoEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 270, 47));

        jchooser.setBackground(new java.awt.Color(255, 255, 255));
        jchooser.setToolTipText("");
        jchooser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jchooserInputMethodTextChanged(evt);
            }
        });
        jchooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jchooserPropertyChange(evt);
            }
        });
        bg.add(jchooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 44, 39));

        campoFechaCita.setBackground(new java.awt.Color(252, 252, 252));
        campoFechaCita.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        campoFechaCita.setShadowColor(new java.awt.Color(0, 153, 153));
        campoFechaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoFechaCitaMouseClicked(evt);
            }
        });
        campoFechaCita.setPlaceholder("Fecha de la cita...");
        bg.add(campoFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        GestionarCitasVista ventana = new GestionarCitasVista();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void codigoEnfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoEnfermedadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEnfermedadMouseClicked

    private void jchooserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jchooserInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jchooserInputMethodTextChanged

    private void jchooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jchooserPropertyChange
        // TODO add your handling code here:
        Date selectedDate = jchooser.getDate();

        if (selectedDate != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = dateFormat.format(selectedDate);
            campoFechaCita.setText(formattedDate);
        }
    }//GEN-LAST:event_jchooserPropertyChange

    private void campoFechaCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoFechaCitaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaCitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarCitaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private ComponentesUI.Button botonGuardar;
    private ComponentesUI.Button botonRegresar;
    private ComponentesUI.TextField campoFechaCita;
    private ComponentesUI.TextField codigoEnfermedad;
    private ComponentesUI.TextArea descripcionCita;
    private ComponentesUI.Combobox estadoCita;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JLabel jLabeltitle1;
    private javax.swing.JLabel jLabeltitle2;
    private javax.swing.JLabel jLabeltitle3;
    private javax.swing.JLabel jLabeltitle4;
    private javax.swing.JLabel jLabeltitle5;
    private javax.swing.JLabel jLabeltitle6;
    private com.toedter.calendar.JDateChooser jchooser;
    private javax.swing.JLabel nombrePaciente;
    private ComponentesUI.TextArea recomendaciones;
    private ComponentesUI.TextAreaScroll textAreaScroll1;
    private ComponentesUI.TextAreaScroll textAreaScroll2;
    private ComponentesUI.TextAreaScroll textAreaScroll3;
    private ComponentesUI.Combobox tipoCita;
    private ComponentesUI.TextArea tratamiento;
    // End of variables declaration//GEN-END:variables
}
